comix_part_deux/config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'
  devise_for :comedians, :controllers => { :omniauth_callbacks => "comedians/omniauth_callbacks" }
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

comix_part_deux/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

comix_part_deux/app/models/club.rb
class Club < ApplicationRecord
  validates :name, presence: true, uniqueness: true
  # validates :name, presence: true
  validates :address, uniqueness: true, presence: true
  # validates :address, presence: true
  has_many :shows
  has_many :comedians, through: :shows

end

comix_part_deux/app/models/comedian.rb
class Comedian < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
   # validates :name, presence: true
   #  validates :username, presence: true


    devise :database_authenticatable, :registerable,
           :recoverable, :rememberable, :validatable, :omniauthable, :omniauth_providers => [:facebook]


           # has_many :jokes
           has_many :jokes, dependent: :destroy
           has_many :shows
           has_many :clubs, through: :shows

  def self.new_with_session(params, session)
    super.tap do |comedian|
      if data = session["devise.facebook_data"] && session["devise.facebook_data"]["extra"]["raw_info"]
        comedian.email = data["email"] if comedian.email.blank?
      end
    end
  end

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |comedian|
      comedian.email = auth.info.email
      comedian.password = Devise.friendly_token[0,20]
      comedian.name = auth.info.name   # assuming the user model has a name
      comedian.image = auth.info.image # assuming the user model has an image
    end
  end
end

comix_part_deux/app/models/joke.rb
class Joke < ApplicationRecord
  validates :topic, presence: true
  validates :punchline, presence: true
  validates :body, presence: true

  belongs_to :comedian
end

comix_part_deux/app/models/show.rb
class Show < ApplicationRecord
  validates :date, presence: true
  validates :start_time, presence: true
  validates :end_time, presence: true

  belongs_to :comedian
  belongs_to :club

end

comix_part_deux/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

comix_part_deux/app/controllers/comedians/omniauth_callbacks_controller.rb
class Comedians::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    @comedian = Comedian.from_omniauth(request.env["omniauth.auth"])

    if @comedian.persisted?
      sign_in_and_redirect @comedian, :event => :authentication
      set_flash_message(:notice, :success, :kind => "Facebook") if is_navigational_format?
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      redirect_to new_comedian_registration_url
    end
  end

  def failure
    redirect_to root_path
  end
end

comix_part_deux/app/controllers/jokes_controller.rb
class JokesController < ApplicationController

  def new
    @joke = Joke.new
  end

  def create
    @joke = Joke.new(joke_params)
    @joke.comedian = User
    if @joke.save
      flash[:success] = "The was so funny I saved it for you."
      redirect_to joke_path(@joke)
    else
      render 'new'
    end
  end


  def edit
  end


private

  def joke_params


  end


end

comix_part_deux/app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def home
  end
  
end

comix_part_deux/app/helpers/application_helper.rb
module ApplicationHelper
end

comix_part_deux/app/helpers/pages_helper.rb
module PagesHelper
end

comix_part_deux/app/views/comedians/new.html.erb
<form action="/signup" method="POST" style="border:1px solid #ccc">
  <div class="container">
    <h3><font face="Source Sans Pro,sans-serif"</font>Create an Account by entering your email and choosing a password.</h3>


      <label for="name"><b>Stage Name:</b></label>
      <input type="text" placeholder="Your stage name" id="name" name="name" required>
    <br><label for="username"><b>Username:</b></label>
    <input type="text" placeholder="Enter a Username" name="username" id="username" required>
    <br><label for="email"><b>Email:</b></label>
    <input type="text" placeholder="Enter your Email" name="email" id="email"required><br>
    <label for="psw"><b>Password:</b></label>
    <input type="password" placeholder="Create a password" id="password" name="password" required>



    <div class="clearfix">
      <br>  <input class="btn btn-primary" style="background-color:#212529" type="submit">
      <br>
      <br><small><a href="/">cancel</a></small>
    </div>
  </div>
</form>

comix_part_deux/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ComixPartDeux</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

comix_part_deux/app/views/pages/home.html.erb
<h1>Welcome to the Comedy Vault - Start creating comedy gold</h1>
<% if current_comedian %>
<div> <%= current_comedian.name%></div>
<%= image_tag(current_comedian.image)%>
<%end%>
<% unless current_comedian %>
  <%= link_to "Sign in with Facebook", comedian_facebook_omniauth_authorize_path %>
<%else%>
  <%=link_to "Logout", destroy_comedian_session_path, method: :delete %>
<%end%>